### Applications and System Tools
bind = CTRL, PRINT, exec, hyprshot -m output -m active -f "Screenshot_$(date +%Y%m%d_%H%M%S).png" -o "/home/aktire/Pictures/Screenshots" -z
bind = Ctrl, SPACE, exec, quickshell -c QuickSnip -n
bind = Meta, N, exec, nautilus Documents/
bind = Meta, PRINT, exec, hyprshot -m window -m active -f "Screenshot_$(date +%Y%m%d_%H%M%S).png" -o "/home/aktire/Pictures/Screenshots" -z
bind = Meta, T, exec, kitty
bind = Super, P, exec, dms ipc call powermenu open
bind = , PRINT, exec, flameshot gui

### Audio Controls
bindl = , XF86AudioMicMute, exec, dms ipc call audio micmute
bindl = , XF86AudioMute, exec, dms ipc call audio mute
bindl = , XF86AudioNext, exec, dms ipc call mpris next
bindl = , XF86AudioPause, exec, dms ipc call mpris pause
bindl = , XF86AudioPlay, exec, dms ipc call mpris play
bindl = , XF86AudioPrev, exec, dms ipc call mpris previous
bindle = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 10
bindle = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 10

### Brightness Controls
bindl = Shift, XF86MonBrightnessDown, exec, dms ipc call brightness decrement 1 backlight:intel_backlight
bindl = Shift, XF86MonBrightnessUp, exec, dms ipc call brightness increment 1 backlight:intel_backlight
bindle = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5 backlight:intel_backlight
bindle = , XF86MonBrightnessUp, exec, dms ipc call brightness increment 5 backlight:intel_backlight

### DMS IPC Services
bind = Alt, space, exec, dms ipc call spotlight toggle
bind = Ctrl Alt, Delete, exec, dms ipc call processlist focusOrToggle
bind = Meta, Comma, exec, dms ipc call settings focusOrToggle
bind = Meta, V, exec, dms ipc call clipboard toggle
bind = Meta, W, exec, dms ipc call dankdash wallpaper
bind = Meta, l, exec, dms ipc call lock lock

### Keyboard and Display
bindl = Meta, B, exec, hyprctl dispatch dpms off
bindl = Meta, Space, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next

### Window Management and Layout
bind = Meta SHIFT, T, togglefloating
bind = Meta SHIFT, V, focuscurrentorlast
bind = Meta, Down, movefocus, down
bind = Meta, F, layoutmsg, fit active
bind = Meta, J, movewindow, left
bind = Meta, K, movewindow, right
bind = Meta, Left, movefocus, l
bind = Meta, Q, killactive
bind = Meta, R, layoutmsg, colresize +conf
bind = Meta, Right, movefocus, r
bind = Meta, Up, movefocus, up
bind = Meta SHIFT, down, movewindow, down
bind = Meta SHIFT, left, layoutmsg, swapcol l
bind = Meta SHIFT, right, layoutmsg, swapcol r
bind = Meta SHIFT, up, movewindow, up
bind = , F11, fullscreen, 0
binde = Meta Shift, Equal, layoutmsg, colresize +0.1
binde = Meta Shift, Minus, layoutmsg, colresize -0.1
binde = Meta, Equal, resizeactive, 0 10%
binde = Meta, Minus, resizeactive, 0 -10%
bindm = Meta, mouse:272, movewindow
bindm = Meta, mouse:273, resizewindow

### Workspace Navigation
bind = Meta, 1, workspace, 1
bind = Meta, 2, workspace, 2
bind = Meta, 3, workspace, 3
bind = Meta, 4, workspace, 4
bind = Meta, 5, workspace, 5
bind = Meta, 6, workspace, 6
bind = Meta, 7, workspace, 7
bind = Meta, 8, workspace, 8
bind = Meta, 9, workspace, 9
bind = Meta, Page_Down, workspace, e+1
bind = Meta, Page_Up, workspace, e-1

### Workspace Transfer
bind = Meta CTRL, 1, movetoworkspace, 1
bind = Meta CTRL, 2, movetoworkspace, 2
bind = Meta CTRL, 3, movetoworkspace, 3
bind = Meta CTRL, 4, movetoworkspace, 4
bind = Meta CTRL, 5, movetoworkspace, 5
bind = Meta CTRL, 6, movetoworkspace, 6
bind = Meta CTRL, 7, movetoworkspace, 7
bind = Meta CTRL, 8, movetoworkspace, 8
bind = Meta CTRL, 9, movetoworkspace, 9
bind = Meta CTRL, Down, movetoworkspace, e+1
bind = Meta CTRL, Up, movetoworkspace, e-1
