## I FUCKING LOVE HYPRLAND!!! and men


## ANIMATIONS

animations {
	enabled = true
	animation = windowsIn, 1, 4, default, popin
	animation = windowsOut, 0, 4, default, popin
	animation = workspaces, 1, 4, default, slidevert
	animation = windowsMove, 1, 4, default, gnomed
	animation = fade, 1, 4, default
	animation = border, 0
}


## DECORATION

decoration {
	active_opacity = 0.85
	inactive_opacity = 0.5
	fullscreen_opacity = 1.0
	dim_inactive = false
	shadow {
		enabled = false
	}
	blur {
		enabled = true
		size = 9
		passes = 3
		xray = false
		popups = true
	}
}


## GENERAL

general {
	layout = scrolling
}


## GESTURES

gestures {
	gesture = 3, vertical, workspace
	gesture = 3, left, dispatcher, movefocus, r
	gesture = 3, right, dispatcher, movefocus, l
}


## ECOSYSTEM

ecosystem {
	no_update_news = true
	no_donation_nag = true
}


## INPUT

input {
    	kb_layout = us, ru
    	numlock_by_default = true
    	touchpad {
        	natural_scroll = true
        	tap-to-click = true
        	clickfinger_behavior = true
    	}
    	follow_mouse = 0
    	touchdevice {
		enabled = true
    	}
}


## MISCELLANEOUS

misc {
    	disable_hyprland_logo = true
    	disable_splash_rendering = true
    	mouse_move_enables_dpms = true
    	animate_mouse_windowdragging = true
}


## MONITOR CONFIGURATION

monitor = eDP-1, 1920x1080, 0x0, 1


## PLUGINS

plugin {
	touch_gestures {
		sensitivity = 8.0
		edge_margin = 10
		workspace_swipe = false
		wokspace_swipe_fingers = 3
		workspace_swipe_edge = 0
		hyprgrass-bind = , edge:r:l, layoutmsg, move +col
		hyprgrass-bind = , edge:l:r, layoutmsg, move -col
		hyprgrass-bind = , pinch:4:i, fullscreen
		hyprgrass-bind = , pinch:4:o, killactive
		hyprgrass-bind = , edge:d:u, exec, kill -34 $(ps -C wvkbd-mobintl) 
	}
}


## SCROLLING LAYOUT

scrolling{
	explicit_column_widths = 0.25, 0.5, 0.75, 1.0
	focus_fit_method = 1
	#wrap_focus = false
	#wrap_swapcol = false
}


## STARTUP

exec-once = systemctl --user start hyprland-session.target
exec-once = dbus-update-activation-environment --systemd --all
exec-once = wayland-pipewire-idle-inhibit -w
exec-once = rfkill unblock bluetooth 
exec-once = hyprpm reload
exec-once = wvkbd-mobintl --hidden -L 360


## SUBSOURCE FILES

source = ./dms/colors.conf
#source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf


## WINDOW AND LAYER RULES

#qs
windowrule = float on, match:class ^(org.quickshell)$
layerrule = no_anim on, match:namespace ^(quickshell)$

#dms
layerrule = no_anim on, match:namespace ^dms:.*

#fullscreen
windowrule = idle_inhibit none, match:fullscreen 1

#steam
windowrule = float on, match:class steam

#screenshot
windowrule = no_anim on, match:class flameshot
windowrule = float on, match:class flameshot

#sessions
windowrule = float on, match:class com.pojtinger.felicitas.Sessions

#xournal
#windowrule = opaque on, match:class com.github.xournalpp.xournalpp
